api:
  path: /api/v${api.version}
  version: 1
spring:
  application:
    name: shop-app
  jackson:
    serialization.write_dates_as_timestamps: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/shopapp?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
server:
  port: 2345



logging:
  level:
    root: ${LOGGING:info}

momo:
  url: http://localhost:4200/payment


jwt:
  expiration: ${TOKEN_EXP:86400}
  secret-key: ${TOKEN_SECRET_KEY:2423bodsagtstor5642ellsdasfu1fts1114asdfvzxb}
#  second
#    30 ngay = 30 * 24 * 60 * 60
#    1 ngay = 24 * 60 * 60
#    1 gio = 60 * 60